"""Second

Revision ID: 2724f486e6bc
Revises: fc1c6c4e263e
Create Date: 2021-06-15 19:18:50.535062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2724f486e6bc'
down_revision = 'fc1c6c4e263e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('names',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_names_id'), 'names', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_names_id'), table_name='names')
    op.drop_table('names')
    # ### end Alembic commands ###
